# -*- coding: utf-8 -*-
"""70. Climbing Stairs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-3lDJB-HgVcwfdoScO09vxVBuZnXgzW
"""

# Dynamic Programming
# Time: O(n)
# Space: O(1)

class Solution:
    def climbStairs(self, n):
        """
        type n: int
        rtype: int
        """
        prev, current = 0, 1
        for i in range(n):
            prev, current = current, prev + current,

        return current